services:
  app_neon:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.neon
    environment:
      CONNECTION_URI: $APP_NEON_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_NEON_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_NEON_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_NEON_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 8953:8080
