global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'otel-collector-job'
    static_configs:
      - targets: ['otel-collector:9091']

storage:
  exemplars:
    max_exemplars: 100000  # Adjust based on your needs
